---

homebrew_taps:
  - {
    tap: "caskroom/cask",
    url: "https://github.com/caskroom/homebrew-cask"
  }
  - {
    tap: "caskroom/fonts",
    url: "https://github.com/caskroom/homebrew-fonts"
  }

homebrew_packages:
  - ansible
  - autoconf
  - bash
  - git
  - git-lfs
  - htop-osx
  - jp2a
  - libav
  - mcrypt
  - md5sha1sum
  - mosh
  - nmap
  - openssh
  - openssl
  - pre-commit
  - pwgen
  - unix2dos
  - unrar
  - wget

homebrew_cask_apps:
  - atom
  - caffeine
  - divvy
  - flux
  - font-anonymous-pro
  - font-bitstream-vera
  - font-hack
  - font-lato
  - font-source-code-pro
  - font-source-sans-pro
  - font-source-serif-pro
  - google-chrome
  - imageoptim
  - lockdown
  - skitch
  - torbrowser
