---

homebrew_taps:
  - caskroom/cask
  - homebrew/dupes
  - homebrew/php
  - homebrew/versions

homebrew_packages:
  - drush
  - git
  - gpg
  - htop-osx
  - libdvdcss
  - mcrypt
  - openssl
  - pandoc
  - wget

homebrew_cask_apps:
  - 1password
  - adobe-reader
  - alfred
  - android-file-transfer
  - atom
  - audio-hijack
  - bartender
  - blueharvest
  - calibre
  - carbon-copy-cloner
  - chocolat
  - cleanmymac
  - codebug
  - codekit
  - crashplan
  - divvy
  - dockertoolbox
  - drobo-dashboard
  - dropbox
  - evernote
  - expandrive
  - firefox
  - flash-player
  - flip4mac
  - flux
  - focused
  - gimp
  - gitkraken
  - gitter
  - google-chrome
  - google-drive
  - gpgtools
  - hazel
  - hobo
  - imageoptim
  - istat-menus
  - iterm2
  - java
  - kaleidoscope
  - kindle
  - kindlegen
  - lastpass
  - libreoffice
  - limechat
  - lockdown
  - omnifocus
  - omnigraffle
  - omnioutliner
  - owncloud
  - quitter
  - rescuetime
  - ripit
  - send-to-kindle
  - sequel-pro
  - skitch
  - slack
  - smartgit
  - smartsynchronize
  - sourcetree
  - sparkleshare
  - time-out
  - torbrowser
  - tower
  - transmission
  - ukelele
  - vagrant
  - vagrant-manager
  - virtualbox
  - virtualbox-extension-pack
  - virtualhostx
  - viscosity
