---

homebrew_taps:
  - caskroom/cask
  - caskroom/fonts
  - homebrew/dupes
  - homebrew/php
  - homebrew/versions
  - jonof/kenutils

homebrew_packages:
  - ansible
  - autoconf
  - awscli
  - bash
  - dos2unix
  - drobo-dashboard
  - drush
  - ffmpeg
  - git
  - git-lfs
  - gnupg
  - gnupg2
  - gpg-agent
  - htop-osx
  - jp2a
  - libav
  - libdvdcss
  - mcrypt
  - md5sha1sum
  - mosh
  - nmap
  - openssh
  - openssl
  - pandoc
  - pngout
  - pre-commit
  - pwgen
  - unix2dos
  - unrar
  - wget
  - youtube-dl

homebrew_cask_apps:
  - 1password
  - adobe-reader
  - alarm-clock
  - alfred
  - amazon-drive
  - amazon-music
  - android-file-transfer
  - atom
  - audio-hijack
  - avira-antivirus
  - bartender
  - bee
  - blueharvest
  - caffeine
  - calibre
  - carbon-copy-cloner
  - cleanmymac
  - codekit
  - cord
  - dash
  - divvy
  - dropbox
  - electrum
  - endurance
  - expandrive
  - filezilla
  - firefox
  - flash-player
  - flip4mac
  - flux
  - focused
  - font-anonymous-pro
  - font-bitstream-vera
  - font-hack
  - font-lato
  - font-source-code-pro
  - font-source-sans-pro
  - font-source-serif-pro
  - fork
  - gimp
  - gitscout
  - gitter
  - google-chrome
  - google-drive
  - gpgtools
  - handbrake
  - hex-fiend
  - hobo
  - horndis
  - imageoptim
  - istat-menus
  - iterm2
  - java
  - kaleidoscope
  - keepassx
  - kindle
  - kindlegen
  - lastpass
  - libreoffice
  - limechat
  - lockdown
  - omnifocus
  - omnigraffle
  - omnioutliner
  - owncloud
  - quitter
  - rescuetime
  - ripit
  - send-to-kindle
  - sequel-pro
  - skitch
  - slack
  - smartgit
  - smartsynchronize
  - sourcetree
  - sparkleshare
  - synergy
  - thunderbird
  - timely
  - torbrowser
  - tower
  - transmission
  - ukelele
  - vagrant
  - vagrant-manager
  - virtualbox
  - virtualbox-extension-pack
  - virtualhostx
  - viscosity
  - vmware-fusion
